# Generated by Django 5.0.2 on 2024-03-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_director',
            field=models.BooleanField(null=True),
        ),
    ]
