# Generated by Django 5.0.2 on 2024-02-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('birth_date', models.DateField()),
                ('age', models.IntegerField()),
                ('awards', models.TextField()),
                ('place_of_birth', models.CharField(max_length=128)),
            ],
        ),
    ]
