# Generated by Django 5.0.2 on 2024-03-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('viewer', '0002_profile_permissions_alter_profile_user_permissions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomPermissions',
        ),
        migrations.AlterField(
            model_name='profile',
            name='permissions',
            field=models.ManyToManyField(to='auth.permission'),
        ),
    ]
