# Generated by Django 5.0.2 on 2024-02-21 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_actor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='awards',
            new_name='awaasdrds',
        ),
    ]
