# Generated by Django 5.0.2 on 2024-03-07 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_delete_custompermissions_alter_profile_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='permissions',
        ),
    ]
