# Generated by Django 5.0.2 on 2024-02-21 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_rename_awards_actor_awaasdrds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='awaasdrds',
            new_name='awards',
        ),
    ]
